name: test_C3_aniso
method: "geostat" # geostat, ml

# paths — set dir_base and dir_input in config.local.yaml (see config.local.yaml.example)

# rho
data_input: "SCI_Sharp_Best_MOD_inv.xyz"
variable_name: "rho"
variable_unit: "Ohm.m"
indicators: [1,2,3,5,10,20,30,50,100]
indicator_bounds: [0.01, 150.0]
doi_name: "doi_standard"

# cl
# data_input: "ZLN-clipped_nmc250_chloride.feather"
# variable_name: "cl"
# variable_unit: "mg/l"
# indicators: [150,300,500,750,1000,1250,1500,2000,3000,5000,7500,10000,15000]
# indicator_bounds: [0.01, 30000.0]

# general variables
epsg: 28992
quantiles: [0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95]
cellsize_xy: 50
cellsize_z: 0.5
buffer_xy: 300
buffer_z: 3
xval_n_lines: 25

#geostat variables
use_anisotropy: True
variogram_model_range_xy: 1000.0
variogram_minor_range_xy_min: 100.0
variogram_model_range_z: 2.01
neighbourhood_dist_xy: 1000.0
neighbourhood_dist_z: 0.99
neighbourhood_n_sectors: 4
neighbourhood_max_neigh_per_sector: 4
    

# ml variables
# OGC_angles: [7.5,22.5,37.5,52.5,67.5,82.5,97.5,112.5,127.5,142.5,157.5,172.5]
rf_n_trees: 200
features: ['z', 'OGC(7.5°)', 'OGC(22.5°)', 'OGC(37.5°)', 'OGC(52.5°)', 'OGC(67.5°)', 'OGC(82.5°)', 'OGC(97.5°)', 'OGC(112.5°)', 'OGC(127.5°)', 'OGC(142.5°)', 'OGC(157.5°)', 'OGC(172.5°)']

# plotting
# plotting_depths: [-150, -50, -10, -5, 0.0]
plotting_layers: [1,7,15,25]
histogram_bins: 50
histogram_sample_size: 10000

# anisotropy
aniso_indicator: 5
aniso_pca_radius: 1000
aniso_pca_nmin: 20
aniso_pca_eig_ratio_min: 2.0
aniso_pca_sampling_eig_min: 2.0
aniso_pca_angle_diff_max: 15.0
aniso_idw_k: 16